### ISSUE TITLE
Como un mayor de edad Necesito poder registrarme Para que pueda vacunarme

### ISSUE THREAD

**Issue by ElChepeCodes** [ADSI-ITAM-2021/LA-MAQUINA-CEMENTERA#3]
- [x] Puedo encontrar a la página fácilmente
- [x] La página da confianza, tiene un diseño profesional
- [x] Existe una forma para poner el CURP
- [x] al subir la forma con el CURP existe retroalimentación de que subió la petición

**Comment by salbertt** [comment]
Redacción no tan clara :/

**Comment by salbertt** [comment]
El comentario que pusieron: 

- Existe una pequeña nota de ayuda
- Se tiene un generador/buscador de CURPs
- Se puede registrar cada usuario una única vez

en realidad no nos dice nada de cuáles son los pasos que siguen les usuaries para llegar ahí. Lo descriptivo de la página va en otro lado, no concierne al usuarie entonces hay que cambiar la redacción. 
Por ejemplo, 
-Si tengo dudas, como usuarie puedo leer la nota de ayuda
