### ISSUE TITLE
Como usuario me gustaría recibir un correo que me recuerde cuándo es mi cita

### ISSUE THREAD

**Issue by ElChepeCodes** [ADSI-ITAM-2021/LA-MAQUINA-CEMENTERA#5]
- [ ] Como usuario me gustaría recibir un correo con al menos 3 días de anticipación
- [ ] El Correo debe tener información confiable para saber que es real
- [ ] El Correo tiene el lugar y la hora de la cita
